language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t meegossh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=TRUE meegossh/docker-react npm run test